# Generated by Django 4.0.3 on 2022-03-27 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_task_user_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='point',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
